# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '学生学习的课程',
                'verbose_name': '学生学习的课程',
            },
        ),
    ]
