# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user', '0002_auto_20171215_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nickname', max_length=20, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(default='openid', max_length=100, verbose_name='微信openid'),
            preserve_default=False,
        ),
    ]
