# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picture_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userPicture', '0002_remove_userpicture_add_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpicture',
            unique_together=set([('user', 'picture')]),
        ),
    ]
